# Generated by Django 6.1.1 on 2026-09-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order_number_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('branch', 'Nova Poshta branch'), ('postomat', 'Nova Poshta parcel locker')], default='branch', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='Nova Poshta city ref'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='Nova Poshta branch ref'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Debit Card'), ('wallet', 'Digital Wallet'), ('cod', 'Cash On Delivery')], default='card', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
