# Generated by Django 6.1.1 on 2026-09-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.TextField(blank=True, verbose_name='адреса доставки за замовчуванням'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='телефон'),
        ),
    ]
