# Generated by Django 6.1.1 on 2026-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_address',
        ),
        migrations.AddField(
            model_name='user',
            name='np_city_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='місто'),
        ),
        migrations.AddField(
            model_name='user',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='ref міста НП'),
        ),
        migrations.AddField(
            model_name='user',
            name='np_delivery_type',
            field=models.CharField(choices=[('branch', 'Відділення Нової Пошти'), ('postomat', 'Поштомат Нової Пошти')], default='branch', max_length=10, verbose_name='спосіб доставки'),
        ),
        migrations.AddField(
            model_name='user',
            name='np_warehouse_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='відділення'),
        ),
        migrations.AddField(
            model_name='user',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='ref відділення НП'),
        ),
    ]
